### ISSUE TITLE
Can you publish device type in response to start_listening

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-client#32]
Almost all other properties are part of start_listening response, having this eliminate my need to call get_propeties.

**Comment by fuatakgun** [comment]
```
start_listening_response:
  name: Entrance
  model: T8113-Z
  serialNumber: somevalue
  hardwareVersion: T8113-Z
  softwareVersion: 5.2.7
  stationSerialNumber: somevalue
  enabled: true
  state: 1
  battery: 80
  batteryTemperature: 25
  lastChargingDays: 8
  lastChargingTotalEvents: 1105
  lastChargingRecordedEvents: 364
  lastChargingFalseEvents: 741
  batteryUsageLastWeek: 0
  motionDetected: false
  personDetected: false
  personName: ''
  antitheftDetection: false
  autoNightvision: true
  ledStatus: true
  motionDetection: true
  rtspStream: false
  watermark: 1
  wifiRSSI: -44
  pictureUrl: somevalue
  motionDetectionType: 2
  motionDetectionSensivity: 14
  microphone: true
  speaker: true
  speakerVolume: 93
  audioRecording: true
  powerSource: 0
  powerWorkingMode: 1
  notificationType: 2
```
```
properties:
  name:
    value: Entrance
    timestamp: 1627398188000
  model:
    value: T8113-Z
    timestamp: 1627398188000
  serialNumber:
    value: somevalue
    timestamp: 1627398188000
  type:
    value: 8
    timestamp: 1627398188000
  hardwareVersion:
    value: T8113-Z
    timestamp: 1627398188000
  softwareVersion:
    value: 5.2.7
    timestamp: 1612754167000
  stationSerialNumber:
    value: somevalue
    timestamp: 1627398188000
  lastChargingDays:
    value: 8
    timestamp: 1627398188000
  lastChargingFalseEvents:
    value: 741
    timestamp: 1627398188000
  lastChargingRecordedEvents:
    value: 364
    timestamp: 1627398188000
  lastChargingTotalEvents:
    value: 1105
    timestamp: 1627398188000
  batteryUsageLastWeek:
    value: 0
    timestamp: 1627398188000
  pictureUrl:
    value: some value
    timestamp: 1627296590000
  rtspStream:
    value: false
    timestamp: 1615749944000
  enabled:
    value: true
    timestamp: 1612263231000
  powerSource:
    value: 0
    timestamp: 1612263234000
  speaker:
    value: true
    timestamp: 1612263234000
  microphone:
    value: true
    timestamp: 1612263234000
  battery:
    value: 83
    timestamp: 1620280047000
  motionDetectionSensivity:
    value: 14
    timestamp: 1615674209000
  speakerVolume:
    value: 93
    timestamp: 1612263234000
  notificationType:
    value: 2
    timestamp: 1615664174000
  statusLed:
    value: true
    timestamp: 1616056809000
  motionDetectionType:
    value: 2
    timestamp: 1615674345000
  wifiRSSI:
    value: -42
    timestamp: 1627414690729
  antitheftDetection:
    value: false
    timestamp: 1612263234000
  motionDetection:
    value: true
    timestamp: 1612263234000
  watermark:
    value: 1
    timestamp: 1612265064000
  state:
    value: 1
    timestamp: 1619015562000
  audioRecording:
    value: true
    timestamp: 1612263234000
  autoNightvision:
    value: true
    timestamp: 1612263234000
  powerWorkingMode:
    value: 1
    timestamp: 1612263236000
  batteryTemperature:
    value: 25
    timestamp: 1620280047000
  motionDetected:
    value: false
    timestamp: 0
  personDetected:
    value: false
    timestamp: 0
  personName:
    value: ''
    timestamp: 0
supported_features: 3
```
